<?php

use Drupal\Core\File\FileExists;
use Drupal\file\Entity\File;

/**
 * Implements hook_install().
 */
function hide_obsolete_files_install() {
  $fids = \Drupal::entityQuery('file')->accessCheck(FALSE)->execute();

  // $fids = [11252];

  foreach ($fids as $fid) {
    if(!getFileUsage($fid)) {
      toggleFileObsolete($fid);
    }
  }
}

/**
 * Gets file usage and checks against current entity revisions.
 */
function getFileUsage(int $fid) {
  $file_usage = \Drupal::service('file.usage');

  $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
  $usage = $file_usage->listUsage($file);

  if (isset($usage['file']['media'])) {
    $usage_list = array_keys($usage['file']['media']);

    foreach ($usage_list as $mid) {
      $media = \Drupal::entityTypeManager()->getStorage('media')->load($mid);
      $media_usage = \Drupal::service('entity_usage.usage')->listSources($media);
      
      foreach ($media_usage['paragraph'] as $paragraph) {
        $in_current_revision = FALSE;

        foreach ($paragraph as $revision) {
          $revision_entity = \Drupal::entityTypeManager()->getStorage('paragraph')->loadRevision($revision['source_vid']);

          if ($revision_entity->isDefaultRevision()) {
            return TRUE;
          }
        }
      }

      foreach ($media_usage['node'] as $node) {
        $in_current_revision = FALSE;

        foreach ($node as $revision) {
          $revision_entity = \Drupal::entityTypeManager()->getStorage('paragraph')->loadRevision($revision['source_vid']);

          if ($revision_entity->isDefaultRevision()) {
            return TRUE;
          }
        }
      }
    }
  }

  return FALSE;
}

/**
 * Adds or removes obsolete flag from filename.
 */
function toggleFileObsolete(int $fid) {
  $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
  $filepath = $file->getFileUri();
  $filepath_obsolete = $filepath . '_obsolete';
  $already_obsolete = str_ends_with($filepath, '_obsolete');
  $has_usage = getFileUsage($file->id());

  if (!$already_obsolete && !$has_usage) {
    $file_system = \Drupal::service('file_system');
    // Rename existing file.
    $file_system->move($file->getFileUri(), $filepath_obsolete, FileExists::Replace);

    $log_args = [
      '%old' => $file->getFilename(),
      '%new' => $filepath_obsolete,
    ];

    // Notify and log.
    $this->logger('file_entity')->info($this->t('File %old renamed to %new'), $log_args);
  }

  if ($already_obsolete && $has_usage) {
    $file_system = \Drupal::service('file_system');
    // Rename existing file.
    $file_system->move($file->getFileUri(), preg_replace('_obsolete', '', $filepath), FileExists::Replace);

    $log_args = [
      '%old' => $file->getFilename(),
      '%new' => $preg_replace('_obsolete', '', $filepath),
    ];

    // Notify and log.
    $this->logger('file_entity')->info($this->t('File %old renamed to %new'), $log_args);
  }
}
