<?php

use Drupal\Core\File\FileExists;
use Drupal\file\Entity\File;

/**
 * Implements hook_install().
 */
function hide_obsolete_files_install() {
  $fids = \Drupal::entityQuery('file')->accessCheck(FALSE)->execute();

  foreach ($fids as $fid) {
    toggleFileObsolete($fid);
  }
}

/**
 * Gets file usage and checks against current entity revisions.
 */
function getFileUsage(int $fid) {
  $file_usage = \Drupal::service('file.usage');

  $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
  $usage = $file_usage->listUsage($file);

  if (isset($usage['file']['media'])) {
    $usage_list = array_keys($usage['file']['media']);

    foreach ($usage_list as $mid) {
      $media = \Drupal::entityTypeManager()->getStorage('media')->load($mid);
      
      if ($media->bundle() === 'document') {
        $media_usage = \Drupal::service('entity_usage.usage')->listSources($media);

        // Scan paragraph usages.
        foreach ($media_usage['paragraph'] as $paragraph) {
          foreach ($paragraph as $revision) {
            $revision_entity = \Drupal::entityTypeManager()->getStorage('paragraph')->loadRevision($revision['source_vid']);
            // Current revision found.
            if ($revision_entity->isDefaultRevision()) {
              return TRUE;
            }
          }
        }

        // Scan node usages.
        foreach ($media_usage['node'] as $node) {
          foreach ($node as $revision) {
            $revision_entity = \Drupal::entityTypeManager()->getStorage('node')->loadRevision($revision['source_vid']);
            // Current revision found.
            if ($revision_entity->isDefaultRevision()) {
              return TRUE;
            }
          }
        }
      }
    }
  }

  return FALSE;
}

/**
 * Adds or removes obsolete flag from filename.
 */
function toggleFileObsolete(int $fid) {
  $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
  $filepath = $file->getFileUri();
  $filepath_obsolete = $filepath . '_obsolete751995';

  $file_system = \Drupal::service('file_system');
  $file_not_obsolete = $file_system->getDestinationFilename($filepath_obsolete, FileExists::Error);

  $file_has_usage = getFileUsage($file->id());

  if ($file_not_obsolete && !$file_has_usage) {
    // Rename existing file by ADDING "_obsolete751995".
    $file_system->move($filepath, $filepath_obsolete, FileExists::Replace);

    // Notify and log.
    \Drupal::logger('hide_obsolete_files')->info('File @old renamed to @new', ['@old' => $filepath, '@new' => $filepath_obsolete]);
  }

  if (!$file_not_obsolete && $file_has_usage) {
    // Rename existing file by REMOVING "_obsolete751995".
    $file_system->move($filepath_obsolete, preg_replace('/_obsolete751995/', '', $filepath), FileExists::Replace);

    // Notify and log.
    \Drupal::logger('hide_obsolete_files')->info('File @old renamed to @new', ['@old' => $filepath, '@new' => $preg_replace('/_obsolete751995/', '', $filepath)]);
  }

  \Drupal::logger('hide_obsolete_files')->info('No files renamed');
}

